name: 参加登録
description: Web Speed Hackathon 2023 の参加登録フォームです
title: "[参加登録]"
labels:
  - registration
body:
  - type: markdown
    attributes:
      value: |
        # ようこそ Web Speed Hackathon 2023 へ！

        - 開催期間 | **2025/02/10 10:30 JST - 2023/03/31 23:59 JST**

        **参加する前に、レギュレーションを確認してください**

         - [注意事項](https://github.com/CyberAgentHack/web-speed-hackathon-2023/blob/main/README.md#注意事項)
         - [レギュレーション](https://github.com/CyberAgentHack/web-speed-hackathon-2023-scoring-tool/blob/main/docs/REGULATION.md)
  - type: dropdown
    id: regulation
    attributes:
      label: "注意事項・レギュレーション {{regulation}}"
      options:
        - 注意事項・レギュレーションを確認して、同意しました
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## 計測対象の URL

        [課題のソースコード](https://github.com/CyberAgentHack/web-speed-hackathon-2023) から、アプリケーションをデプロイして、URL を提出してください
  - type: input
    id: target-url
    attributes:
      label: "計測対象の URL {{url}}"
      placeholder: e.g.) https://web-speed-hackathon-2023.example.com/
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## 準備が整いました

        投稿すると、GitHub Actions によって自動計測が始まります！

        - :information_source: もし、 1 分以上何も反応がない場合は、 a01sa01to に連絡してください
